#include "TilesPatterns.h"

const TilesPattern corridorPatterns[CORRIDOR_PATTERNS] = {	/*Nº 1*/TilesPattern(CORRIDOR_TILES, false, false, true, true, true, true, true, true, true, true, true, true, true, true,
																								 true, false, true, false, false, false, true, true, true, true, true, true, true, true),
															/*Nº 2*/TilesPattern(CORRIDOR_TILES, false, false, true, false, true, false, true, true, true, true, true, true, true, true,
																								 true, true, true, true, false, false, false, true, false, true, true, true, true, true),
															/*Nº 3*/TilesPattern(CORRIDOR_TILES, true, true, true, false, false, false, false, true, true, true, true, true, true, true,
																								 true, true, true, true, true, true, false, true, false, false, true, false, true, true),
															/*Nº 4*/TilesPattern(CORRIDOR_TILES, true, true, true, true, false, true, false, true, false, true, false, true, true, true,
																								 true, true, true, true, true, true, true, true, true, false, true, false, false, false),
															/*Nº 5*/TilesPattern(CORRIDOR_TILES, true, true, true, true, true, true, true, true, false, true, false, true, false, false,
																								 true, true, true, true, true, true, true, true, true, true, false, true, false, true),
															/*Nº 6*/TilesPattern(CORRIDOR_TILES, false, false, true, true, true, true, true, true, true, false, true, false, true, false,
																								 true, false, true, false, true, true, true, true, true, true, true, true, true, true),
															/*Nº 7*/TilesPattern(CORRIDOR_TILES, false, false, true, false, true, false, true, true, true, true, true, true, true, true,
																								 true, false, true, false, false, false, true, true, true, true, true, true, true, true),
															/*Nº 8*/TilesPattern(CORRIDOR_TILES, true, true, true, false, false, false, false, true, true, true, true, true, true, true,
																								 true, true, true, true, false, false, false, true, false, true, true, true, true, true),
															/*Nº 9*/TilesPattern(CORRIDOR_TILES, true, true, true, true, false, true, false, true, false, true, false, true, true, true,
																								 true, true, true, true, true, true, false, true, false, false, true, false, true, true),
															/*Nº 10*/TilesPattern(CORRIDOR_TILES, true, true, true, true, true, true, true, true, false, true, false, true, false, false,
																								  true, true, true, true, true, true, true, true, true, false, true, false, false, false),
															/*Nº 11*/TilesPattern(CORRIDOR_TILES, true, true, true, true, true, true, true, true, true, false, true, false, true, false,
																								  true, false, true, false, true, true, true, true, true, true, false, true, false, true) };

const TilesPattern arenaPattern1 = TilesPattern(ARENA_TILES, true, true, true, true, true, true, true, true, true, true,
	true, true, true, true, true, true, true, true, true, true,
	true, true, true, true, false, false, false, false, false, false,
	false, false);
const TilesPattern arenaPattern2 = TilesPattern(ARENA_TILES, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, true, true, true, true, true,
	true, true);
const TilesPattern arenaPattern3 = TilesPattern(ARENA_TILES, true, true, true, false, true, true, true, true, true, false,
	true, true, true, true, true, false, true, true, true, true,
	true, false, true, true, true, false, true, false, true, false,
	true, false);

const TilesPattern bossPatternsNormal[BOSS_PATTERNS_NORMAL] = {	/*Nº 1*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false, 
																								 false, false, false, false, false, false, false, false, true, false, true), 
																/*Nº 2*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								 false, false, false, false, false, false, false, true, true, true, true),
																/*Nº 3*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								 false, true, false, false, false, false, true, true, false, true, false),
																/*Nº 4*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								 true, true, false, false, false, true, true, false, false, false, false),
																/*Nº 5*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, true,
																								 true, false, false, false, true, true, false, false, false, false, false),
																/*Nº 6*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, true, true,
																								 false, false, false, true, true, false, false, false, false, false, false),
																/*Nº 7*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, true, true, false,
																								 false, false, true, true, false, false, false, false, false, false, false),
																/*Nº 8*/TilesPattern(BOSS_TILES, false, false, false, true, false, false, false, true, true, false, false,
																								 false, false, true, false, false, false, false, false, false, false, false),
																/*Nº 9*/TilesPattern(BOSS_TILES, false, false, true, true, false, false, true, true, false, false, false,
																								 false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 10*/TilesPattern(BOSS_TILES, false, true, true, false, false, true, true, false, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 11*/TilesPattern(BOSS_TILES, true, true, false, false, true, true, false, false, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 12*/TilesPattern(BOSS_TILES, true, false, false, false, true, false, false, false, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 13*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								  false, false, false, false, false, false, false, true, false, true, false),
																/*Nº 14*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								  false, false, false, false, false, false, false, true, true, true, true),
																/*Nº 15*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, true,
																								  false, false, false, false, true, false, false, false, true, false, true),
																/*Nº 16*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, true,
																								  true, false, false, false, true, true, false, false, false, false, false),
																/*Nº 17*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																								  true, true, false, false, false, true, true, false, false, false, false),
																/*Nº 18*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, true, false, false,
																								  false, true, true, false, false, false, true, false, false, false, false),
																/*Nº 19*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, true, true, false,
																								  false, false, true, true, false, false, false, false, false, false, false),
																/*Nº 20*/TilesPattern(BOSS_TILES, true, false, false, false, true, false, false, false, false, true, false,
																								  false, false, false, true, false, false, false, false, false, false, false),
																/*Nº 21*/TilesPattern(BOSS_TILES, true, true, false, false, true, true, false, false, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 22*/TilesPattern(BOSS_TILES, false, true, true, false, false, true, true, false, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 23*/TilesPattern(BOSS_TILES, false, false, true, true, false, false, true, true, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false),
																/*Nº 24*/TilesPattern(BOSS_TILES, false, false, false, true, false, false, false, true, false, false, false,
																								  false, false, false, false, false, false, false, false, false, false, false) };

const TilesPattern bossPatternsInterphase[BOSS_PATTERNS_INTERPHASE] = {	/*Nº 1*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, false, false, false,
																										 false, false, false, false, false, false, false, true, true, true, true),
																		/*Nº 2*/TilesPattern(BOSS_TILES, false, false, false, false, false, false, false, false, true, true, true,
																										 true, true, true, true, true, true, true, false, false, false, false),
																		/*Nº 3*/TilesPattern(BOSS_TILES, true, true, true, true, true, true, true, true, false, false, true,
																										 true, true, false, false, true, true, true, false, false, false, false),
																		/*Nº 4*/TilesPattern(BOSS_TILES, true, true, true, true, true, true, true, true, false, false, false,
																										 false, false, false, false, false, false, false, false, false, false, false),
																		/*Nº 5*/TilesPattern(BOSS_TILES, true, true, false, false, false, false, true, true, true, true, false,
																										 false, false, false, false, false, false, false, false, false, false, false),
																		/*Nº 6*/TilesPattern(BOSS_TILES, true, true, false, false, false, false, true, true, true, true, true,
																										 false, false, false, false, false, false, true, true, true, false, false),
																		/*Nº 7*/TilesPattern(BOSS_TILES, true, true, false, false, false, false, true, true, true, true, true,
																										 true, false, false, false, false, true, true, true, true, false, false),
																		/*Nº 8*/TilesPattern(BOSS_TILES, true, true, false, false, false, false, true, true, true, true, true,
																										 true, true, false, false, true, true, true, true, true, false, false),
																		/*Nº 9*/TilesPattern(BOSS_TILES, false, false, true, true, true, true, false, false, false, false, false,
																										 false, false, true, true, false, false, false, false, false, false, false),
																		/*Nº 10*/TilesPattern(BOSS_TILES, false, false, true, true, true, true, false, false, false, false, false,
																										  false, true, true, true, true, false, false, false, false, true, true),
																		/*Nº 11*/TilesPattern(BOSS_TILES, false, false, true, true, true, true, false, false, false, false, false,
																										  true, true, true, true, true, true, false, false, false, true, true),
																		/*Nº 12*/TilesPattern(BOSS_TILES, false, false, true, true, true, true, false, false, false, false, true,
																										  true, true, true, true, true, true, true, false, false, true, true) };
